/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const App = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'emoji' : IDL.Text,
});
export const Settings = IDL.Record({
  'backgroundEffect' : IDL.Text,
  'wallpaper' : IDL.Text,
  'accentColor' : IDL.Text,
  'showClock' : IDL.Bool,
  'openInIframe' : IDL.Bool,
  'taskbarPosition' : IDL.Text,
});

export const idlService = IDL.Service({
  'addApp' : IDL.Func([App], [], []),
  'deleteApp' : IDL.Func([IDL.Text], [], []),
  'getApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'updateApp' : IDL.Func([App], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const App = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'emoji' : IDL.Text,
  });
  const Settings = IDL.Record({
    'backgroundEffect' : IDL.Text,
    'wallpaper' : IDL.Text,
    'accentColor' : IDL.Text,
    'showClock' : IDL.Bool,
    'openInIframe' : IDL.Bool,
    'taskbarPosition' : IDL.Text,
  });
  
  return IDL.Service({
    'addApp' : IDL.Func([App], [], []),
    'deleteApp' : IDL.Func([IDL.Text], [], []),
    'getApps' : IDL.Func([], [IDL.Vec(App)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'updateApp' : IDL.Func([App], [], []),
    'updateSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };